/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Shell-Execute.h
 #	source generated by 4D Plugin Wizard
 #	Project : Shell Execute
 #	author : miyako
 #	2021/10/27
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_SHELL_EXECUTE_H
#define PLUGIN_SHELL_EXECUTE_H

#include "4DPluginAPI.h"

#include "C_TEXT.h"

#pragma mark -

#if VERSIONWIN
#include <tlhelp32.h>
#include <shlwapi.h>
#include <Shlguid.h>
#endif

#include "4DPlugin-JSON.h"

void Find_best_application(PA_PluginParameters params);
void GET_PROCESS_LIST(PA_PluginParameters params);
void OPEN_WITH_APPLICATION(PA_PluginParameters params);
void PRINT_WITH_APPLICATION(PA_PluginParameters params);

#endif /* PLUGIN_SHELL_EXECUTE_H */
